HyperParams:
    valid_size: 0.2
    batch_size: 64
    num_splits: 5
    num_workers: 0
    num_epochs: 10
    step_size: 10
    lr: 0.001
    seed: 42

Auxiliary:
    ROOT_PATH: './'
    DATA_PATH: 'data/'
    ORIGINAL_DATA: 'RawData.xlsx'
    OTHER_DATA: 'otherdata.csv'
    DTI_DATA: 'DTIconnectivity.csv'
    RS_DATA: 'RestingState.csv'
    COR_DATA: 'Corticalthickness.csv'
    OUTCOME: 'outcome.csv'