MODALITIES:
    - 'dti'
    - 'rs'
    - 'other'
    - 'cort'

METRICS:
    - 'accuracy'
    - 'precision'
    - 'recall'

DTI:
    architecture: 'mlp'
    layers:
        - 20
        - 40
        - 20
    
RS:
    architecture: 'mlp'
    layers:
        - 100
        - 100
        - 100
    
CORT:
    architecture: 'mlp'
    layers:
        - 50
        - 150
        - 50
    
OTHER:
    architecture: 'mlp'
    layers:
        - 20

Auxiliary:
    ROOT_PATH: './'
    DATA_PATH: 'data/'
    ORIGINAL_DATA: 'RawData.xlsx'
    OTHER_DATA: 'otherdata.csv'
    DTI_DATA: 'DTIconnectivity.csv'
    RS_DATA: 'RestingState.csv'
    COR_DATA: 'Corticalthickness.csv'
    OUTCOME: 'outcome.csv'